#!/bin/bash


#--singularity exec ./unicycler_0.5.0--py310hc8f18ef_2.sif /usr/local/bin/unicycler $*

singularity exec /global/software/rocky-8.x86_64/manual/modules/apps/bio/unicycler/0.5.0/unicycler_0.5.0--py310hc8f18ef_2.sif  /usr/local/bin/unicycler $*

# source
# singularity pull docker://quay.io/biocontainers/unicycler:0.5.0--py310hc8f18ef_2
